# Import libraries

In [37]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras

In [38]:
tf.__version__

'2.17.1'

# Import Dataset

In [39]:
df = pd.read_csv("Churn_Modelling.csv")
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

# Data Cleaning

In [40]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [41]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [42]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers= [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X=np.array(ct.fit_transform(X))


In [43]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [44]:
print(X[0])

[1.0 0.0 0.0 619 0 42 2 0.0 1 1 1 101348.88]


In [45]:
print(X[1])

[0.0 0.0 1.0 608 0 41 1 83807.86 1 0 1 112542.58]


In [46]:
print(X[2])

[1.0 0.0 0.0 502 0 42 8 159660.8 3 1 0 113931.57]


In [47]:
print(X[1, 0:4])

[0.0 0.0 1.0 608]


# Spliting train test data

In [48]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =0.2, random_state = 42)

# Feature Scaling

In [49]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [50]:
print(X_train)

[[ 1.00150113 -0.57946723 -0.57638802 ...  0.64920267  0.97481699
   1.36766974]
 [-0.99850112  1.72572313 -0.57638802 ...  0.64920267  0.97481699
   1.6612541 ]
 [-0.99850112 -0.57946723  1.73494238 ...  0.64920267 -1.02583358
  -0.25280688]
 ...
 [ 1.00150113 -0.57946723 -0.57638802 ... -1.54035103 -1.02583358
  -0.1427649 ]
 [ 1.00150113 -0.57946723 -0.57638802 ...  0.64920267 -1.02583358
  -0.05082558]
 [-0.99850112  1.72572313 -0.57638802 ...  0.64920267  0.97481699
  -0.81456811]]


# Building Neural Network Model

In [51]:
ann = tf.keras.models.Sequential()     #initialising ann
ann.add(tf.keras.layers.Dense(units = 6, activation='relu'))   #first layer
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))  #second layer
ann.add(tf.keras.layers.Dense(units =1, activation = 'sigmoid')) #output layer

In [52]:
#compiling the ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [53]:
#Training the ANN
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7675 - loss: 0.6100
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7885 - loss: 0.4945
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7873 - loss: 0.4642
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8026 - loss: 0.4335
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7994 - loss: 0.4229
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8029 - loss: 0.4161
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8090 - loss: 0.4044
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8381 - loss: 0.4086
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8538 - loss: 0.3744
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8470 - loss: 0.3773
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8537 - loss: 0.3712
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━

In [54]:
#making predictions
print(ann.predict(sc.transform([[1, 0, 0, 60, 0, 50, 3, 600, 2, 1, 1, 500]]))>0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 200ms/step
[[False]]


# Confusion Matrix and Accuracy

In [56]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred=ann.predict(X_test)
y_pred=(y_pred>0.5)
cm=confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[1545   62]
 [ 215  178]]
0.8615
